name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly-2026-03-31
          override: true
          components: rustfmt
      - name: Check formatting of all crates in the workspace
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo test --all
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --locked

  msrv:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: 1.84.0
          override: true
      - name: Run cargo test (excluding golden/ui tests)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --exclude dynosaur_ui_tests --locked
